### ISSUE TITLE
gff3_sq_remove_redundant_entries.pl error

### ISSUE THREAD

**Issue by life404** [NBISweden/GAAS#12]
I'm training my own species model by using Augustus. I want to get the gff3 file without redundancy proteins. And I don't know how to do this, so I hope the perl script, gff3_sq_remove_redundant_entries.pl can help me to do this.
But, I fount a error in this script, when I try to using it, it put the error to me
```shell
Global symbol "$help" requires explicit package name (did you forget to declare "my $help"?) at ./gff3_sq_remove_redundant_entries.pl line 38.
Execution of ./gff3_sq_remove_redundant_entries.pl aborted due to compilation errors.
```
And I also want to know, whether this scripts can remove the redundancy proteins from gff3?

**Comment by Juke34** [comment]
Now fixed.
The script just remove redundant entries: same   seq_id (1st column) ,primary_tag(3rd column),start ,stop.
In order to train augustus properly it is not the way to go. Have a look here: https://nbisweden.github.io/workshop-genome_annotation/labs/augustus_training

In one of the step you will have to blast your translated CDS all against all, and remove sequences that are too similar to each other ( over 80% identity).
