### ISSUE TITLE
gaas_maker_merge_outputs_from_datastore.pl does not create the  maker_mix.gff file anymore

### ISSUE THREAD

**Issue by LucileSol** [NBISweden/GAAS#64]
Hi,
I ran gaas_maker_merge_outputs_from_datastore.pl on the genome.maker.output folder of maker the 30th of September and no maker_mix.gff was created.
Last time I ran the script and created a  maker_mix.gff file was on 29th on july (on an other species).
I ran gaas_maker_merge_outputs_from_datastore.pl on the same folder as the 29th of july but no maker_mix.gff was created.

I checked the git log but I don't see anything that was done that would change gaas_maker_merge_outputs_from_datastore.pl 

any ideas?

Thank you,

Lucile

**Comment by Juke34** [comment]
hey hey, this line did not change years,
but the next line has been modified by Nima 5 month ago:
 https://github.com/NBISweden/GAAS/blob/4cebe38ec06a7e2d0ea58bf700d5c2a55f8e50c6/bin/gaas_maker_merge_outputs_from_datastore.pl#L273
You should try with the previous code to see if this change has introduced the error, otherwise it is related to the input file... and code to handle this case must be updated.
